### ISSUE TITLE
Cross-covariance prediction

### ISSUE THREAD

**Issue by arincbulgur** [pmorenoz/ContinualGP#2]
Hi @pmorenoz, I am planning to use your algorithm for a multi-output gaussian process problem. Normally, I was training a `Gpy.models.SparseGPCoregionalizedRegression` model in an offline manner, but I want to switch to an online algorithm as I need to improve the model on-the-fly. I have tried to modify `multi_output.py` in this repo for my case, but I couldn't clear a hurdle. So, I need to predict a full covariance matrix, which is the cross-covariance matrix between different outputs. To clarify what I mean, if the output dimension is d and I feed a single input to the model, I am expecting to get a d-by-d covariance matrix. `Gpy.models.SparseGPCoregionalizedRegression` model was allowing it because it was creating its own coregionalized kernel. When I check `svmogp.py` or `continualgp.py` in this repo, it looks like you're creating a coregionalized kernel while forming the B matrices but you're not using it. Instead you're updating the parameters of individual kernels for each latent function and then using them for the prediction. I haven't completely understood your paper so I am not sure if it's possible to make predictions using coregionalized kernel. But if it's possible can you show me how I can do it?

**Comment by pmorenoz** [comment]
Hi @arincbulgur, thanks for your question. The continual setup of the MOGP in the repository has a special mechanism, based on the inducing points. The main goal is to "avoid forgetting" as new data is observed in new input areas that have not been modeled very well. This knowledge is compressed in the inducing points Z, that in the case of MOGPs, lies on the latent functions U (not in the output functions F as in the standard single-output case). That's the reason why you have probably seen a lot of manipulations around this individual functions and their kernels. The problem with W, and hyperparameters is analogous to this. So, in the variational continual scenario that we consider, we only build the corregionalized kernel at each step for obtaining the prediction of output functions F, evaluating them with the expected likelihood probabilities and checking if the lower bound is augmenting.

If you explicitly need this corregionalized kernel/matrix, you can obtain it from the elements mentioned, just building it at the end of each iteration. I have some code for this in the [HetMOGP](https://github.com/pmorenoz/HetMOGP/) repository. Particularly, in hetmogp>util.py. See LCM and cross_covariance methods. The syntax of both codes is the same one. Hope it helps!
